create table if not exists public.crm_mappings (
  id bigint generated by default as identity primary key,
  order_id text not null unique,
  twenty_person_id text,
  twenty_opportunity_id text,
  twenty_note_id text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.crm_mappings enable row level security;

create policy "twenty_api runner"
on public.crm_mappings
for all
to service_role
using (true)
with check (true);

create policy "anon read limited"
on public.crm_mappings
for select
to anon
using (false);

-- alias note: this env backend authenticates as service_role for full mutations
